### ISSUE TITLE
webhook error

### ISSUE THREAD

**Issue by okineadev** [kentaro-m/auto-assign-action#181]
![image](https://github.com/kentaro-m/auto-assign-action/assets/81070564/36772951-ed13-4a36-a9f2-6b489dc5d869)

**Comment by adamkudrna** [comment]
@okineadev The error message is not very helpful, but it seems it happens when you are trying to launch this action with an event trigger **other than [`pull_request`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)**. In such case, the [pull request context is not available](https://github.com/kentaro-m/auto-assign-action/blob/53bd294f719872cba08cf030b9ee21ffe6ce406c/src/handler.ts#L33) which leads to this error.

**Comment by okineadev** [comment]
So there will be no correction?

**Comment by adamkudrna** [comment]
This is just my observation, I'm passing by just like you 🙂.
